# 02 — Matrices

This notebook builds core matrix operations from scratch
(`src/matrix_operations.py`): multiplication, transpose, and the identity
matrix, each checked against NumPy.

In [1]:
import sys
sys.path.insert(0, "../src")

import numpy as np
np.set_printoptions(precision=4, suppress=True)


## Define two example matrices

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A, B

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

## Matrix multiplication

$$(AB)_{ij} = \sum_k A_{ik} B_{kj}$$

Matrix multiplication is composition of linear transformations — this is
the single most-used operation in machine learning (every layer of a
neural network is, at its core, a matrix multiplication).

In [3]:
from matrix_operations import matrix_multiply

print("A @ B (mine):\n", matrix_multiply(A, B))
print()
print("A @ B (numpy):\n", A @ B)

A @ B (mine):
 [[19. 22.]
 [43. 50.]]

A @ B (numpy):
 [[19 22]
 [43 50]]


## Transpose

$$(A^T)_{ij} = A_{ji}$$

In [4]:
from matrix_operations import transpose

print("A.T (mine):\n", transpose(A))
print()
print("A.T (numpy):\n", A.T)

A.T (mine):
 [[1. 3.]
 [2. 4.]]

A.T (numpy):
 [[1 3]
 [2 4]]


## Identity matrix

$AI = A$ for any matrix $A$ — verified below.

In [5]:
from matrix_operations import identity, matrix_multiply

I = identity(2)
print("I:\n", I)
print()
print("A @ I (should equal A):\n", matrix_multiply(A, I))

I:
 [[1. 0.]
 [0. 1.]]

A @ I (should equal A):
 [[1. 2.]
 [3. 4.]]


## Why this matters for ML

Matrix multiplication is how data flows through a neural network layer:
`output = activation(W @ x + b)`. Understanding it at the element level
demystifies backpropagation, which is fundamentally the chain rule applied
across a sequence of matrix multiplications.

Next notebook: linear transformations — what matrices actually *do*
geometrically.